name: Test (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Test [no features]
      run: cargo test --verbose

    - name: Test ['full' feature]
      run: cargo test --verbose --features full